name: condominio_app
description: SmartCondominium mobile app
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  gap: ^3.0.1
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  go_router: ^16.2.4
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  flutter_local_notifications: ^19.4.2
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/illustrations/
